### ISSUE TITLE
Could DataLoad work for less memory?

### ISSUE THREAD

**Issue by jhzao82** [mcekovic/tennis-crystal-ball#308]
I am not sure the DataLoad will use how many memory, And It's not very fit to my host, My question is Could DataLoad work for less memory even less CPU?

**Comment by mcekovic** [comment]
DataLoad needs at least 256MB heap (-Xmx256m)
However, such small amount of heap do affect performance, you need 512 MB or 1 GB for full speed.
UTS production uses 256MB heap by default.
Further reducing memory requirements for DataLoad would significantly affect its performance.

**Comment by mcekovic** [comment]
I have run full data load on production couple of days before  with 256 MB heap on Linux and now on Windows on dev machine with also max 256 MB heap (completed in 35 min, 15 of which are for Wikipedia player data). I was using JDK 1.8 64 bit in both cases.

**Comment by mcekovic** [comment]
2 GB is enough for OS, PostgreSQL, Web App and Data Load, this is the amount of RAM UTS production is using. Both Web App and Data Load should use 256 MB heaps.

**Comment by jhzao82** [comment]
I have pulled right now, It's a going to work now, It's so exited! But, still have some error.

Failed to execute: REFRESH MATERIALIZED VIEW player_surface_goat_points because: An I/O error occurred while sending to the backend.

Caught exception rolling back connection: This connection has been closed.
Exception in thread "main" org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:791)
	at groovy.sql.Sql.rollback(Sql.java:3470)
	at groovy.sql.Sql$rollback$4.call(Unknown Source)
	at org.strangeforest.tcb.dataload.SqlPool.withTx(SqlPool.groovy:62)
	at org.strangeforest.tcb.dataload.SqlPool$withTx$0.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
	at org.strangeforest.tcb.dataload.SqlPool$withTx$0.callStatic(Unknown Source)
	at org.strangeforest.tcb.dataload.SqlPool.withSql(SqlPool.groovy:42)
	at org.strangeforest.tcb.dataload.SqlPool$withSql.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.strangeforest.tcb.dataload.LoadATPTennis.run(LoadATPTennis.groovy:31)
	at org.strangeforest.tcb.dataload.LoadATPTennis$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
	at org.strangeforest.tcb.dataload.Main.run(Main.groovy:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1235)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at org.strangeforest.tcb.dataload.Main.main(Main.groovy)

**Comment by mcekovic** [comment]
Seems that PostgreSQL is out of memory.
Check you settings in /etc/postgresql/10/main/postgresql.conf, 256 MB should be enough.
shared_buffers = 256MB

**Comment by jhzao82** [comment]
My setting is 128M, I am tring hope this time will success!

**Comment by mcekovic** [comment]
128MB is too low, I had similar problems before with 128MB (previously my host had only 512 RAM to OS)
