### ISSUE TITLE
data-loader 10th step issue

### ISSUE THREAD

**Issue by maxdemo2** [mcekovic/tennis-crystal-ball#338]
Hi,

I am getting an error in the 10th step of #232 issue. 
When I run : `data-load-1.0-SNAPSHOT/bin/data-load.bat -lt -c 10 -bd %full path of tennis_atp data directory by Jeff Sackmann%`

I get this error : 

`Loading Tennis Data
Allocating DB connections..........
Loading players
Loading file 'C:\Users\maxde\tennis_atp\atp_players.csv'
....................................................................................................
..........
Rows: 54880 in 9.798 s (6097 row/s)

Loading additional player data
Loading file 'classpath:/player-data.xml'
Exception in thread "main" java.util.NoSuchElementException: Cannot find player Jo Wilfried Tsonga
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
        at org.strangeforest.tcb.dataload.SimpleXMLLoader.loadItem(SimpleXMLLoader.groovy:21)
        at org.strangeforest.tcb.dataload.SimpleXMLLoader$loadItem.callCurrent(Unknown Source)
        at org.strangeforest.tcb.dataload.BaseXMLLoader.loadFile(BaseXMLLoader.groovy:33)
        at org.strangeforest.tcb.dataload.BaseXMLLoader$loadFile.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.ATPTennisLoader.loadAdditionalPlayerData(ATPTennisLoader.groovy:92)
        at org.strangeforest.tcb.dataload.ATPTennisLoader$loadAdditionalPlayerData$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.LoadATPTennis$_run_closure1.doCall(LoadATPTennis.groovy:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.SqlPool.withTx(SqlPool.groovy:50)
        at org.strangeforest.tcb.dataload.SqlPool$withTx$0.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.strangeforest.tcb.dataload.SqlPool$withTx$0.callStatic(Unknown Source)
        at org.strangeforest.tcb.dataload.SqlPool.withSql(SqlPool.groovy:41)
        at org.strangeforest.tcb.dataload.SqlPool$withSql.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.LoadATPTennis.run(LoadATPTennis.groovy:12)
        at org.strangeforest.tcb.dataload.LoadATPTennis$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.strangeforest.tcb.dataload.Main.run(Main.groovy:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
        at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at _org.strangeforest.tcb.dataload.Main.main(Main.groovy)`_

Thanks !

**Comment by mcekovic** [comment]
>> Data loader has been updated to reflect recent changes in Jeff's
atp_tennis repo (as of commit cf2201c on 2 dec 2019) as well as recent
changes in official ATP web site data

Try reverting your copy of Jeff's repo to commit cf2201c on 2 dec 201,
because UTS currently supports data only as of this commit.

**Comment by maxdemo2** [comment]
I still get the same error :(

**Comment by mcekovic** [comment]
Sorry, you need to recreate the DB schema (or clean it) after reverting
working copy of Jeff's repo.

MC

**Comment by maxdemo2** [comment]
Thank you for,your help ! It was working well when I unfortunately got this error : 

`
Loading additional match data
Fetching tournament URL 'https://www.atptour.com/en/scores/archive/bournemouth/347/1968/results'
31 matches loaded in 1.193 s
Fetching tournament URL 'https://www.atptour.com/en/scores/archive/london/311/1968/results'
53 matches loaded in 1.509 s
Fetching tournament URL 'https://www.atptour.com/en/scores/archive/dublin/2029/1968/results'
15 matches loaded in 1.048 s
Fetching tournament URL 'https://www.atptour.com/en/scores/archive/buenos-aires/303/1968/results'
15 matches loaded in 1.228 s
Fetching tournament URL 'https://www.atptour.com/en/scores/archive/perth/243/1969/results'
Exception in thread "main" java.text.ParseException: Unparseable date: "-"
        at java.base/java.text.DateFormat.parse(DateFormat.java:395)
        at java_text_DateFormat$parse.call(Unknown Source)
        at org.strangeforest.tcb.dataload.BaseXMLLoader.date(BaseXMLLoader.groovy:89)
        at org.strangeforest.tcb.dataload.BaseXMLLoader$date$0.callStatic(Unknown Source)
        at org.strangeforest.tcb.dataload.ATPTourTournamentLoader.scrapeResults(ATPTourTournamentLoader.groovy:67)
        at org.strangeforest.tcb.dataload.ATPTourTournamentLoader$scrapeResults$1.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.strangeforest.tcb.dataload.ATPTourTournamentLoader$scrapeResults$1.callCurrent(Unknown Source)
        at org.strangeforest.tcb.dataload.ATPTourTournamentLoader.loadTournament(ATPTourTournamentLoader.groovy:40)
        at org.strangeforest.tcb.dataload.ATPTourTournamentLoader.loadTournament(ATPTourTournamentLoader.groovy)
        at org.strangeforest.tcb.dataload.ATPTourTournamentLoader$loadTournament$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.strangeforest.tcb.dataload.ATPTennisLoader.loadAdditionalTournamentData(ATPTennisLoader.groovy:117)
        at org.strangeforest.tcb.dataload.ATPTennisLoader$loadAdditionalTournamentData$4.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.LoadATPTennis$_run_closure4.doCall(LoadATPTennis.groovy:20)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:37)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.SqlPool.withTx(SqlPool.groovy:50)
        at org.strangeforest.tcb.dataload.SqlPool$withTx$0.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.strangeforest.tcb.dataload.SqlPool$withTx$0.callStatic(Unknown Source)
        at org.strangeforest.tcb.dataload.SqlPool.withSql(SqlPool.groovy:41)
        at org.strangeforest.tcb.dataload.SqlPool$withSql.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.strangeforest.tcb.dataload.LoadATPTennis.run(LoadATPTennis.groovy:20)
        at org.strangeforest.tcb.dataload.LoadATPTennis$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.strangeforest.tcb.dataload.Main.run(Main.groovy:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:423)
        at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at org.strangeforest.tcb.dataload.Main.main(Main.groovy)`

**Comment by mcekovic** [comment]
ATP website has lost the date for Perth 1969: https://www.atptour.com/en/scores/archive/perth/243/1969/results
You can try to pull latest commits from UTS Git repo, recreate the UTS DB and try again, but nothing is guaranteed.
Alternatively you can take a look at https://github.com/mcekovic/tennis-crystal-ball/issues/337

**Comment by maxdemo2** [comment]
It is now the tournament of Durban in 1969 which stop the execution. 
Is it possible to avoid the load of those additional matches ?
Thanks for your time.

**Comment by mcekovic** [comment]
Unfortunately ATP has introduced Clouflare anti-bot/anti-scrapping protection and it is not possible anymore to easily scrape ATP web site.
